#!/usr/bin/env sh

make > make.log || exit

if test ".$(../../../bin/bout-config --has-openmp)" == .yes
then
    ml=1 2 3 4 5
else
    ml=1
fi

for n in 1 2 4
do
    for m in $ml
    do
	if ! OMP_NUM_THREADS=$m mpirun -np $n ./test_dataiterator > run.log.$m.$n
        then
            err=$?
            echo failing command was:
            echo OMP_NUM_THREADS=$m mpirun -np $n ./test_dataiterator
            echo
            echo error log was:
            cat run.log.$m.$n
            echo
            exit $?
        fi
    done
done

echo "All test successfull"
